stages:
  - build
  - deploy_gcp

build-images: 
  stages: build
  image: docker:20.10.16

  services:
    - docker: 20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_scripts:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t ricardocardoso72/app-cicd-dio:1.0 app/.
    - docker push ricardocardoso72/app-cicd-dio:1.0
    
deploy_gcp:

  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH-KEY

  script:
      - ssh -o StrictHostKeyChecking-no - i $SSH_SERVER "sudo rm -RF ./app-cicd-dio/ && ..."