stages:
  - build
build-images: 
  stages: build
  image: docker:20.10.16

  services:
    - docker: 20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_scripts:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t ricardocardoso72/app-cicd-dio:1.0 app/.
    - docker push ricardocardoso72/app-cicd-dio:1.0