apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: minhaappsegura
spec:
  domains:
    - minhaappsegura.ricardocardoso.com.br
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minhaappsegura-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: minhaappsegura
    networking.gke.io/managed-certificates: minhaappsegura
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ssl-only: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  defaultBackend:
    service:
      name: frontend-external
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080